name: ğŸš€ Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted


    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ” Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: ğŸš€ SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SERVER_IP }} << 'EOF'
            cd /home/vishwajeet/zanfintech/zan-fintech-solutions

            echo "ğŸ”„ Pulling latest code"
            git reset --hard
            git pull origin master

            echo "ğŸ“¦ Backend setup"
            source backend/venv/bin/activate
            cd backend
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            cd ..

            echo "ğŸ›  Building frontend"
            cd frontend
            npm install
            npm run build
            cd ..

            echo "ğŸ“ Copy frontend build to staticfiles"
            rm -rf backend/staticfiles/*
            cp -r frontend/dist/* backend/staticfiles/

            echo "â™»ï¸ Restarting backend"
            sudo supervisorctl restart zanbackend
          EOF
